/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;

import static Client.LoginForm.user;
import Common.KMessage;
import Common.Users;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.plaf.TableUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Ranking extends javax.swing.JFrame{
    ListenServer listenServer;
    public Users user;
    ArrayList<Users> usList;
    /**
     * Creates new form Ranking
     * @throws java.io.IOException
     */
    public Ranking(ListenServer listenServer, ArrayList<Users> usList) throws IOException {
        initComponents();
        this.listenServer = listenServer;
        this.usList = usList;
        loadTableUser();
    }
    
    private void loadTableUser(){
        int flag = 0;
//        DefaultTableModel model = new DefaultTableModel();
//        model.addColumn("Ranking");
//        model.addColumn("UserName");
//        model.addColumn("Win");
//        model.addColumn("Lose");
//        model.addColumn("Score");
//        JTable table = new JTable(model);
//        table.setVisible(true);
//        for(Users u : this.usList){
//            int i=1;
//            model = (DefaultTableModel) table.getModel();
//            model.addRow(new Object[]{i, u.getUsername(), u.getWin(), u.getLose(), u.getScore()});
//            i++;
//        }
        int i =1;
        Vector vctHeader = new Vector();
        Vector vctData = new Vector();
        vctHeader.add("Ranking");
        vctHeader.add("Username");
        vctHeader.add("Win");
        vctHeader.add("Lose");
        vctHeader.add("Score");
        for(Users u : this.usList){
        Vector vt = new Vector();
            vt.add(i);
            vt.add(u.getUsername());
            vt.add(u.getWin());
            vt.add(u.getLose());
            vt.add(u.getScore());
            if(u.getId() == this.user.getId())
                flag = i;
            i++;
            vctData.add(vt);
        }
        jTable1.setModel(new DefaultTableModel(vctData,vctHeader));
//        if(flag > 0){
//            jLabel1.setText(Integer.toString(flag));
//            jLabel2.setText(this.user.getUsername());
//            jLabel3.setText(Integer.toString(this.user.getWin()));
//            jLabel4.setText(Integer.toString(this.user.getLose()));
//            jLabel5.setText(Integer.toString(this.user.getScore()));
//        }
//        else{
//            jLabel1.setText("chưa");
//            jLabel2.setText("đủ 10");
//            jLabel3.setText("trận");
//            jLabel4.setText("không thể");
//            jLabel5.setText("xếp hạng");
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Back");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:    
                    //JOptionPane.showMessageDialog(null, "Ok", "Message", 1);

                    /* Create and display the form */
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                            //new Main(listenServer).setVisible(true);
                            new RoomFrame(listenServer).setVisible(true);
                        }
                    });
                    //this.setVisible(false);
                    this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
